### ISSUE TITLE
error: Cannot read property 'fileName' of undefined

### ISSUE THREAD

**Issue by dcharkes** [Gruntfuggly/format-modified#1]
Hey, I love this plugin!

Unfortunately, it has stopped working for me a couple of weeks back. If I try to manually execute `> Format modified sections` from the command menu I get an error `Cannot read property 'fileName' of undefined`.

(VSCode's format on save subsequently formats the whole file, which is not what I would like.)

I'm unfamiliar with debugging VSCode plugins, is there a way I can get a stack trace for this error to figure out what's going on?

Note that the file has a `.cc` extension (as I noticed we switched from file extensions to languages).

**Comment by Gruntfuggly** [comment]
It's OK - I can reproduce it. I have it set to format on save so I haven't used the command directly for a while, which is how it's got broken without me noticing. I'll sort it out.

formatOnSave shouldn't format the whole file unless you have another extension formatting it somehow?

**Comment by Gruntfuggly** [comment]
I've uploaded a new version which should now work from the command prompt again.

**Comment by dcharkes** [comment]
Great, it works again from the command menu!

> formatOnSave shouldn't format the whole file unless you have another extension formatting it somehow?

I'm not sure which plugin that might be. I tried disabling the standard `"C_Cpp.formatting": "Disabled"`, but that didn't work.

**Comment by Gruntfuggly** [comment]
I just realised - there is a case where it formats the whole file - when the file is not in git. Is it possible that is what was happening?
