### ISSUE TITLE
"Failed to fetch diffs" error on every attempt to format

### ISSUE THREAD

**Issue by HighCommander4** [Gruntfuggly/format-modified#10]
The extension has stopped working for me recently: on every attempt to format a file, I get an error popup saying "Failed to fetch diffs".

How can I diagnose this further / get more information about the error?

**Comment by HighCommander4** [comment]
Hmm maybe it has to do with the fact that I'm currently resolving merge conflicts?

**Comment by HighCommander4** [comment]
So yeah, after resolving merge conflicts the extension is working fine again.

Is this a known issue, that it doesn't work when your working copy is in a merge conflict state?

Could it gracefully fall back to whole-file formatting in such cases?

**Comment by Gruntfuggly** [comment]
Yes, it could do something a bit nicer. I'll look into it.

**Comment by Gruntfuggly** [comment]
The latest version now detects files with merge conflicts are generates a more appropriate warning. 

Formatting the whole document would have caused problems due to the merge conflicts.
