### ISSUE TITLE
Another "Failed to fetch diffs" error

### ISSUE THREAD

**Issue by bartekn-chromium** [Gruntfuggly/format-modified#11]
I just installed this extension and always get "Failed to fetch diffs". That doesn't seem to be https://github.com/Gruntfuggly/format-modified/issues/10 because I am not in the middle of a merge.

My configuration is as follows (and I double checked existence of clang-format under this path):
{
  "format-modified.executable": "/usr/bin/clang-format",
  "editor.formatOnPaste": true,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "Gruntfuggly.format-modified"
}

The Dev Console shows this stack when "Failed to fetch diffs" was thrown:
  | onDidChangeNotification | @ | notificationsAlerts.ts:40
-- | -- | -- | --
  | (anonymous) | @ | notificationsAlerts.ts:26
  | fire | @ | event.ts:587
  | addNotification | @ | notifications.ts:183
  | notify | @ | notificationService.ts:101
  | (anonymous) | @ | mainThreadMessageService.ts:83
  | _showMessage | @ | mainThreadMessageService.ts:44
  | $showMessage | @ | mainThreadMessageService.ts:38
  | _doInvokeHandler | @ | rpcProtocol.ts:398
  | _invokeHandler | @ | rpcProtocol.ts:383
  | _receiveRequest | @ | rpcProtocol.ts:299
  | _receiveOneMessage | @ | rpcProtocol.ts:226
  | (anonymous) | @ | rpcProtocol.ts:101
  | fire | @ | event.ts:587
  | fire | @ | ipc.net.ts:453
  | _receiveMessage | @ | ipc.net.ts:733
  | (anonymous) | @ | ipc.net.ts:592
  | fire | @ | event.ts:587
  | acceptChunk | @ | ipc.net.ts:239
  | (anonymous) | @ | ipc.net.ts:200
  | t | @ | ipc.net.ts:28
  | emit | @ | events.js:203
  | addChunk | @ | _stream_readable.js:295
  | readableAddChunk | @ | _stream_readable.js:276
  | Readable.push | @ | _stream_readable.js:210

**Comment by Gruntfuggly** [comment]
There should be a debug channel (Format Modified) in the Output view. Can you have a look in there and see what the output is?

**Comment by Gruntfuggly** [comment]
A silly question maybe - but I assume the file is in a git repository?

**Comment by bartekn-chromium** [comment]
Yes, the file is in a git repo.

I didn't see Format Modified in the Output tab, but copying couple others that may or may not be useful...

Git:
> git status -z -u
> git symbolic-ref --short HEAD
> git rev-parse CP_OperatorEq
> git rev-parse --symbolic-full-name CP_OperatorEq@{u}
> git rev-list --left-right CP_OperatorEq...refs/remotes/origin/master
> git for-each-ref --format %(refname) %(objectname) --sort -committerdate
> git remote --verbose
> git config --get commit.template

Clang Language Server
I[12:00:07.908] Failed to find compilation database for /usr/local/google/home/bartekn/chromium2/src/third_party/blink/renderer/core/layout/layout_table_row_test.cc
I[12:00:07.908] ASTWorker building file /usr/local/google/home/bartekn/chromium2/src/third_party/blink/renderer/core/layout/layout_table_row_test.cc version 2 with command clangd fallback
[/usr/local/google/home/bartekn/chromium2/src/third_party/blink/renderer/core/layout]
/usr/lib/llvm-9/bin/clang /usr/local/google/home/bartekn/chromium2/src/third_party/blink/renderer/core/layout/layout_table_row_test.cc -fsyntax-only -resource-dir=/usr/lib/clangd/lib/clang/google3-trunk
I[12:00:07.908] Failed to find compilation database for /usr/local/google/home/bartekn/chromium2/src/base/memory/checked_ptr.h
I[12:00:07.908] ASTWorker building file /usr/local/google/home/bartekn/chromium2/src/base/memory/checked_ptr.h version 5 with command clangd fallback
[/usr/local/google/home/bartekn/chromium2/src/base/memory]
/usr/lib/llvm-9/bin/clang -xobjective-c++-header /usr/local/google/home/bartekn/chromium2/src/base/memory/checked_ptr.h -fsyntax-only -resource-dir=/usr/lib/clangd/lib/clang/google3-trunk
I[12:00:07.911] --> textDocument/clangd.fileStatus
I[12:00:07.912] --> textDocument/clangd.fileStatus
I[12:00:07.912] --> textDocument/clangd.fileStatus
I[12:00:07.912] --> textDocument/clangd.fileStatus
I[12:00:09.486] <-- textDocument/codeAction(59)
I[12:00:09.486] --> reply:textDocument/codeAction(59) 0 ms
I[12:00:09.486] --> textDocument/clangd.fileStatus

**Comment by Gruntfuggly** [comment]
Sorry - the debug isn't enabled by default. Can you set `format-modified.debug` to `true`. There should then be a channel available from the drop down on the output panel (called Format Modified) which should have the debug log in it.

**Comment by bartekn-chromium** [comment]
That really helped! The logs told me that the differ dies. And it dies, because I set it up to start meld and env variable DISPLAY isn't set up.

I don't know `git diff` well. Is there a way for you to run the algorithm of your choice, without me having to unconfigure meld?

**Comment by Gruntfuggly** [comment]
Hmm -  not sure. How have you configured the git diff? By specifying difftool?

**Comment by bartekn-chromium** [comment]
In ~/.gitconfig:
[diff]
       external = /path/to/my/git-diff.sh

**Comment by Gruntfuggly** [comment]
Looks like you need to specify `--no-ext-diff` as an argument. I'll update the extension.

**Comment by bartekn-chromium** [comment]
Thank you for working on this tool! It's great.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version. Can you let me know if it works for you?

**Comment by bartekn-chromium** [comment]
It's working great now, thank you!
