### ISSUE TITLE
Shows merge conflict error when file is not in repo

### ISSUE THREAD

**Issue by Gruntfuggly** [Gruntfuggly/format-modified#12]

**Comment by konradsa** [comment]
I have a question on this one: format-modified still complains about a merge conflict market even after all merge conflicts have been fixed. Only after I commit the changes to git it stops complaining. Is it possible to detect that all merge conflicts have been fixed without the need to commit to git?

**Comment by Gruntfuggly** [comment]
It will work once you've staged the changes in the files you have fixed the conflicts in. 

What do you use for fixing conflicts? If you use a separate tool like meld, you can set `trustExitCode` to true in git config and it will automatically staged the fixed conflicts.

**Comment by Gruntfuggly** [comment]
The alternative would be to search the file for conflict markers, but that would be a bit messy and possibly prone to errors.

**Comment by Gruntfuggly** [comment]
Ah - I may have just found an easier way...

**Comment by konradsa** [comment]
Yeah, it's kind of confusing after you fix all the conflicts in the file, format-modified still complains that it can't format since there are conflict markers.

**Comment by Gruntfuggly** [comment]
Just uploaded a new version with a better check for conflicts. Please let me know how you get on with it.

**Comment by konradsa** [comment]
Very cool, let me try it out.
