### ISSUE TITLE
Don't format if change set cannot be detected

### ISSUE THREAD

**Issue by konradsa** [Gruntfuggly/format-modified#13]
Hi,

First of all thank you for this great extension!

Would it be possible to add an option to not do clang-format if changeset cannot be detected? I work with files that are symlinked by the build system, and if I open a file via a symlink (e.g. from the compiler output) then it looks like Vscode doesn't see it as part of the git repo. When I save now, FormatModified ends up formatting the entire file even if only a single line was changed, which is not desired.

Thanks

**Comment by Gruntfuggly** [comment]
Yes, the current fallback option is to format the file - I could make that configurable. 

However, without the extension, would it not normally format the whole file anyway?

**Comment by konradsa** [comment]
That would be awesome, thanks! I sometimes format whole files without noticing and then when creating the PR I have to painfully undo these formatting changes. 

Don't think Vscode formats whole file without the extension, only if you have something like "Editor: Format On Save" turned on, but that is off by default.

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version with an option to turn off whole document formatting on failure.
Set `format-modified.formatWholeDocumentOnFailure` to `false`.

**Comment by konradsa** [comment]
Thanks so much for the quick update, will give it a whirl.
