### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joshburkart** [Gruntfuggly/format-modified#2]
Great extension! Thanks so much for releasing it. I'd love to pick up recent changes (specifically adding the `format=file` arg to `clang-format`) -- can a new release be published? Thanks!

**Comment by Gruntfuggly** [comment]
I'm not sure I understand? The extension uses whatever version of clang-format you have installed. You can tell it to use a particular binary by setting `format-modified.clang-format` or it will try to use whatever version is in your path.

Or do you just mean you'd like to pass extra arguments to clang-format?

**Comment by joshburkart** [comment]
Oh, I just meant that the version I get when I install the extension from within VSCode doesn't seem to have the most recent code changes? In particular, a recent PR added passing `-format=file` as an arg to `clang-format`, so I was hoping to pick up that change.

Sorry for the confusion!

**Comment by Gruntfuggly** [comment]
This one doesn't install clang-format itself. Are you using the one that comes with the C++ extension, or the self contained clang-format extension?

**Comment by joshburkart** [comment]
I'm referring to the arguments that get passed to `clang-format`... [This commit](https://github.com/Gruntfuggly/format-modified/commit/ab212173c0cec834ee68b3f04ae34e883e69925f) added an additional arg to pass (`-style=file`, which makes `clang-format` "load style configuration from `.clang-format` file located in one of the parent directories of the source file"). However, the [version available on the VSCode extension pane](https://marketplace.visualstudio.com/items/Gruntfuggly.format-modified/changelog) doesn't seem to include this particular commit. So I was hoping the extension could be updated. :)

**Comment by Gruntfuggly** [comment]
Ah - I'm with you now! Will do...

**Comment by Gruntfuggly** [comment]
Hi - I'm sorry it's taken so long to do this - it slipped off my radar. I just need to do a bit more testing, but I should be able to release a new version tomorrow (with some other new features).

**Comment by Gruntfuggly** [comment]
I've just uploaded a new version.
