### ISSUE TITLE
an idea 

### ISSUE THREAD

**Issue by ctf0** [Gruntfuggly/format-modified#7]
can we extract the code for showing the modified lines into another plugin that shows them in the gutter ?

same as git but without having to init a git project

**Comment by Gruntfuggly** [comment]
It uses git to find the modified lines. It must have a git repo to compare the file against. Or have I misunderstood?

**Comment by ctf0** [comment]
ah ok, i thought the ext doesnt need that.

however we cld instead on first change to the opened file, save a temp file and use it to compare against the new changes & delete the temp on file close.

**Comment by Gruntfuggly** [comment]
Doesn't vscode show modifications in the gutter already? Or do you mean track even after saving?

**Comment by ctf0** [comment]
sadly no, file have to be in a git project, u can try with any file saved outside git and test for ur self

**Comment by ctf0** [comment]
sadly no, file have to be in a git project, u can try with any file saved outside git and test for ur self

**Comment by ctf0** [comment]
sadly no, file have to be in a git project, u can try with any file saved outside git and test for ur self

**Comment by Gruntfuggly** [comment]
Yeah - I see what you mean. It could be done, but the problem is that there is no way in vscode to detect when a file is closed. I have tried to do this in other extensions, but the onClosed event does not fire reliably. We would end up with temporary files everywhere. I suppose it could be configured to put them somewhere out of the way though.

However, if feels like it's probably a completely different extension to this one. I'll see what I can come up with though...

**Comment by ctf0** [comment]
for the temp files issues we can use it in 2 ways
- remove the files via a command or interval ex.a week
- use the temp files as an undo history file for the saved one, ofcourse we will need a place to save what temp file relates to which saved file.

and yes it was an idea for a diff ext that use some of this ext logic

**Comment by ctf0** [comment]
hi again, i made something that might solve this https://github.com/ctf0/vscode-show-unsaved-changes

i believe u r more experienced than me, so if possible maybe we can collaborate to get it in shape 👍

**Comment by Gruntfuggly** [comment]
Hi - I had a quick look, but haven't got much time at the moment. Happy to help though!

**Comment by ctf0** [comment]
sure np, take ur time

**Comment by Gruntfuggly** [comment]
Sorry I never got any further looking at this, but it looks like you nailed it. Nice use of the comment provider for deletions!

**Comment by ctf0** [comment]
thanks for ur sweet reply.

for the comments i couldn't find a way to show them as readonly  "without the reply input box", do u happen to know a way around ?

**Comment by Gruntfuggly** [comment]
No, I've only just started looking at the comment provider myself - I've got an extension for code reviews where it would work really well - currently I use text decorations which is a bit horrible.

If I find anything I'll let you know.

**Comment by ctf0** [comment]
awesome, thanx again
