### ISSUE TITLE
Using the extension from a docker container

### ISSUE THREAD

**Issue by ghost** [Gruntfuggly/format-modified#9]
First of all thank you for this plugin it's a god send.

I am trying to use this plugin using the setup described [here](https://code.visualstudio.com/docs/remote/containers) where the VsCode server would be running on a container and the host OS would only be running the UI part of VsCode.

So as part of the container configuration I am installing the format-modified extension on the VsCode server as can be seen below:

```
"extensions": [
	"twxs.cmake",
	"stkb.rewrap",
	"albert.tabout",
	"ms-vscode.cpptools",
	"gruntfuggly.format-modified"
]
```

The settings I have on the remote machine are shown below
```
{
	"format-modified.debug": true,
	"format-modified.executable": "/usr/bin/clang-format-9",
	"terminal.integrated.shell.linux": "/bin/bash",
	"format-modified.languages": [
		"cpp"
	],
	"[cpp]": {
		"editor.formatOnSave": true,
		"editor.wordBasedSuggestions": false
	}
}
```

The problem I'm facing is that when I save a file (that has some changes) the automatic format on save call is not triggered and therefore the file is not modified. If I trigger the action manually using the command *Format Modified: Format modified sections* then it works without any problems. Is there an additional setting that I am missing or does this extension does not support remote yet?

If it helps, the below is the output I get when I trigger the formatOnSave manually
```
Manual format, starting job 1
1> Formatting /workspace/modules/http/src/handlers/PreAuthSecureTrading.cpp
1> Relative path: modules/http/src/handlers/PreAuthSecureTrading.cpp
1> Fetching diffs for PreAuthSecureTrading.cpp in /workspace/modules/http/src/handlers using:
1>  git show :modules/http/src/handlers/PreAuthSecureTrading.cpp | git diff -U0 --no-index --exit-code --no-color -- - /root/.vscode-server/data/User/globalStorage/gruntfuggly.format-modified/PreAuthSecureTrading.cpp
1> Ranges:["-lines=20:20"]
1> Using clang-format executable defined by 'format-modified.executable': /usr/bin/clang-format-9
1> Formatting using:
1>  /usr/bin/clang-format-9 -style=file -lines=20:20
1> in folder /workspace/modules/http/src/handlers
1> Format complete
1> Restoring previous cursor position
```

---

Container Details
---
OS: Ubuntu 18.04
Clang Format Version: 9

Host OS
---
macOS Catalina version 10.15.4

VsCode Version: 1.43.2

**Comment by Gruntfuggly** [comment]
There is a general vscode setting **Editor: Format On Save** (`editor.formatOnSave`)  which needs to be set to `true`.

Sorry - just noticed you've got it set as a cpp setting - can you try it globally?

**Comment by Gruntfuggly** [comment]
You should see something in the output window like
```
Formatter triggered for <filename>
```
If it's being triggered.

**Comment by ghost** [comment]
The `editor.formatOnSave` flag is being set to true for c++ only files as shown in the settings
```
"editor.formatOnSave": true,
```
or should this also be in VsCode's general settings not just the remote?

**Comment by Gruntfuggly** [comment]
Just updated my earlier comment :grin:

Can you try the general settings and see if it makes a difference?

**Comment by Gruntfuggly** [comment]
Actually, that probably won't make a difference. 
Currently, it uses a document selector with the scheme "file". Maybe it needs something to work with remote files?

**Comment by ghost** [comment]
This article might help you: https://code.visualstudio.com/api/advanced-topics/remote-extensions

**Comment by Gruntfuggly** [comment]
Would you be prepared to do a bit of hacking to try something?

If you go to the extension source `~/.vscode/extensions/Gruntfuggly.format-modified-0.0.26/extension.js` (or similar) and edit line 229 to remove the 'scheme' attribute, ie.
```
documentSelector.push( { language: language } );
```
Then restart and see if it works?

**Comment by Gruntfuggly** [comment]
If that isn't possible - I'm not familiar with how extensions are located which containers - I'll add a configuration setting to allow the scheme to be modified.

**Comment by ghost** [comment]
I solved it by using the [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command) extension which called the format modified function and then saves the file and set it to the Ctrl + s keybinding. Let me know if you need more details and I'll give you all the required JSON settings.

**Comment by Gruntfuggly** [comment]
Yes, I'd be interested. I'll take a look at the multi-command extension and see how it sets up it's file watcher.

**Comment by Gruntfuggly** [comment]
Having looked into this, I don't think it's even possible to select multiple schemes. I'm not sure I understand how it works remotely, but as you have a workaround, I'm going to close this.
